version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-dev
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-dev
    command: celery -A celery_app.celery_client worker --pool=threads -l info
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./ghost_mesh_fe
      dockerfile: Dockerfile
      target: dev
    container_name: frontend-dev
    volumes:
      - ./ghost_mesh_fe:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: always
